# Generated by Django 3.1.7 on 2021-02-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('cuisine', models.TextField()),
                ('ingredients', models.TextField()),
                ('directions', models.TextField()),
                ('image', models.TextField()),
            ],
        ),
    ]
